name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */1 *'
  push:

env:
  REGISTRY_IMAGE: gmazzo/kotlin

jobs:
  fetch-versions:
    name: Fetch Kotlin versions
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.fetch.outputs.versions }}
    steps:
      - name: Fetch Kotlin versions
        id: fetch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "versions=$(gh --repo JetBrains/kotlin release list --exclude-drafts --exclude-pre-releases --json tagName,isLatest --jq '[.[] | select(.isLatest) | .tagName | sub("^v"; "")]')" >> "$GITHUB_OUTPUT"

  build:
    name: Build kt${{ matrix.kotlin-version }}-${{ matrix.base-image }}
    needs: fetch-versions
    uses: ./.github/workflows/build-flavor.yaml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        kotlin-version: ${{ fromJSON(needs.fetch-versions.outputs.versions) }}
        base-image:
          - eclipse-temurin:21
          - eclipse-temurin:21-alpine
          - amazoncorretto:21
          - amazoncorretto:21-alpine
          - azul/zulu-openjdk:21
          - azul/zulu-openjdk-alpine:21
    with:
      kotlin-version: ${{ matrix.kotlin-version }}
      base-image: ${{ matrix.base-image }}
      latest: ${{ matrix.base-image == 'eclipse-temurin:21-alpine' }}
