name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */1 *'
  push:

env:
  REGISTRY_IMAGE: gmazzo/kotlin

jobs:
  fetch-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.fetch.outputs.versions }}
    steps:
      - name: Fetch Kotlin versions
        id: fetch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "versions=$(gh --repo JetBrains/kotlin release list --exclude-drafts --exclude-pre-releases --json tagName,isLatest --jq '[.[] | select(.isLatest) | .tagName | sub("^v"; "")]')" >> "$GITHUB_OUTPUT"

  build:
    name: kt${{ matrix.kotlin-version }}-jdk${{ matrix.java-version }}-${{ matrix.distribution }}
    needs: fetch-versions
    uses: ./.github/workflows/build-flavor.yaml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        kotlin-version: ${{ fromJSON(needs.fetch-versions.outputs.versions) }}
        java-version:
          - 21
        java-vendor:
          - eclipse-temurin
        distribution:
          - alpine
          - ubuntu
    with:
        kotlin-version: ${{ matrix.kotlin-version }}
        java-version: ${{ matrix.java-version }}
        java-vendor: ${{ matrix.java-vendor }}
        distribution: ${{ matrix.distribution }}
        latest: ${{ matrix.distribution == 'alpine' }}
