name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */1 *'
  push:

env:
  REGISTRY_IMAGE: gmazzo/kotlin

jobs:
  fetch-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.fetch.outputs.versions }}
    steps:
      - name: Fetch Kotlin versions
        id: fetch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "versions=$(gh --repo JetBrains/kotlin release list --exclude-drafts --exclude-pre-releases --json tagName,isLatest --jq '[.[] | select(.isLatest) | .tagName | sub("^v"; "")]')" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs:
      - fetch-versions
    strategy:
      fail-fast: false
      matrix:
        kotlin: ${{ fromJSON(needs.fetch-versions.outputs.versions) }}
        java-version:
          - 21
        java-vendor:
          - eclipse-temurin
        distribution:
          - alpine
          - ubuntu
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Prepare
        env:
          TEMPLATE: kt${{ matrix.kotlin }}-jdk${{ matrix.java-version }}-${{ matrix.java-vendor }}-${{ matrix.platform }}-${{ matrix.distribution }}
        run: |
          echo "DISCRIMINATOR=${TEMPLATE//\//-}" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=kt${{ matrix.kotlin }}
            type=raw,value=jdk${{ matrix.java-version }}-${{ matrix.java-vendor }}
            type=raw,value=${{ matrix.distribution }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          build-args: |
            KOTLIN_VERSION=${{ matrix.kotlin }}
            JAVA_VERSION=${{ matrix.java-version }}
            JAVA_VENDOR=${{ matrix.java-vendor }}
            DISTRIBUTION=${{ matrix.distribution }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.DISCRIMINATOR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: type=raw,value=latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
